[package]
name = "fundsp"
description = "Audio processing and synthesis library."
keywords = ["dsp", "audio", "synthesizer", "sound", "wave"]
license = "MIT OR Apache-2.0"
version = "0.12.0"
authors = ["SamiPerttu <Sami.Perttu@gmail.com>"]
homepage = "https://github.com/SamiPerttu/fundsp"
repository = "https://github.com/SamiPerttu/fundsp"
readme = "README.md"
edition = "2021"

[dependencies]
generic-array = "0.14.7"
numeric-array = "0.5.2"
num-complex = "0.4.3"
rustfft = "6.1.0"
lazy_static = "1.4.0"
tinyvec = { version = "1.6.0", features = ["alloc"] }
rsor = "0.1.3"
duplicate = "1.0.0"
dyn-clone = "1.0.11"
symphonia = { version = "0.5.2", optional = true, features = ["aac", "alac", "mp3", "isomp4"] }
thingbuf = "0.1.3"
funutd = "0.11.0"

[features]
default = ["files"]
files = ["dep:symphonia"]

[dev-dependencies]
cpal = "0.15.2"
anyhow = "1.0.70"
plotters = "0.3.4"
criterion = "0.4.0"
midi-msg = "0.4.0"
midir = "0.9.1"
read_input = "0.8.6"
assert_no_alloc = "1.1.2"

[[bench]]
name = "benchmark"
harness = false

[[example]]
name = "beep"
path = "examples/beep.rs"

[[example]]
name = "peek"
path = "examples/peek.rs"

[[example]]
name = "sequence"
path = "examples/sequence.rs"

[[example]]
name = "type"
path = "examples/type.rs"

[[example]]
name = "plot"
path = "examples/plot.rs"

[[example]]
name = "file"
path = "examples/file.rs"

[[example]]
name = "grain"
path = "examples/grain.rs"

[[example]]
name = "grain2"
path = "examples/grain2.rs"

[[example]]
name = "network"
path = "examples/network.rs"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
